/*
 * traQ v3
 *
 * traQ v3 API
 *
 * The version of the OpenAPI document: 3.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct AddUserGroupMemberRequest {
    /// ユーザーUUID
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    /// ユーザーの役割
    #[serde(rename = "role")]
    pub role: String,
}

impl AddUserGroupMemberRequest {
    pub fn new(id: uuid::Uuid, role: String) -> AddUserGroupMemberRequest {
        AddUserGroupMemberRequest { id, role }
    }
}
