/*
 * traQ v3
 *
 * traQ v3 API
 *
 * The version of the OpenAPI document: 3.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// ChannelPath : チャンネルパス

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ChannelPath {
    /// チャンネルパス
    #[serde(rename = "path")]
    pub path: String,
}

impl ChannelPath {
    /// チャンネルパス
    pub fn new(path: String) -> ChannelPath {
        ChannelPath { path }
    }
}
