/*
 * traQ v3
 *
 * traQ v3 API
 *
 * The version of the OpenAPI document: 3.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GetMyStampRecommendations200ResponseInner {
    /// スタンプUUID
    #[serde(rename = "stampId")]
    pub stamp_id: uuid::Uuid,
    /// レコメンドスコア
    #[serde(rename = "score")]
    pub score: f64,
}

impl GetMyStampRecommendations200ResponseInner {
    pub fn new(stamp_id: uuid::Uuid, score: f64) -> GetMyStampRecommendations200ResponseInner {
        GetMyStampRecommendations200ResponseInner { stamp_id, score }
    }
}
