/*
 * traQ v3
 *
 * traQ v3 API
 *
 * The version of the OpenAPI document: 3.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// QallSoundboardItemCreatedEvent : Qallのサウンドボードアイテムが作成された

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct QallSoundboardItemCreatedEvent {
    /// 作成されたサウンドボードアイテムのId
    #[serde(rename = "soundId")]
    pub sound_id: uuid::Uuid,
    /// 作成されたサウンドボードアイテムの名前
    #[serde(rename = "name")]
    pub name: String,
    /// 作成者のId
    #[serde(rename = "creatorId")]
    pub creator_id: uuid::Uuid,
}

impl QallSoundboardItemCreatedEvent {
    /// Qallのサウンドボードアイテムが作成された
    pub fn new(
        sound_id: uuid::Uuid,
        name: String,
        creator_id: uuid::Uuid,
    ) -> QallSoundboardItemCreatedEvent {
        QallSoundboardItemCreatedEvent {
            sound_id,
            name,
            creator_id,
        }
    }
}
