/*
 * traQ v3
 *
 * traQ v3 API
 *
 * The version of the OpenAPI document: 3.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// QallSoundboardItemCreatedEvent : Qallのサウンドボードアイテムが作成された

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct QallSoundboardItemCreatedEvent {
    /// 作成されたサウンドボードアイテムのId
    #[serde(rename = "soundId", skip_serializing_if = "Option::is_none")]
    pub sound_id: Option<uuid::Uuid>,
    /// 作成されたサウンドボードアイテムの名前
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// 作成者のId
    #[serde(rename = "creatorId", skip_serializing_if = "Option::is_none")]
    pub creator_id: Option<uuid::Uuid>,
}

impl QallSoundboardItemCreatedEvent {
    /// Qallのサウンドボードアイテムが作成された
    pub fn new() -> QallSoundboardItemCreatedEvent {
        QallSoundboardItemCreatedEvent {
            sound_id: None,
            name: None,
            creator_id: None,
        }
    }
}
