/*
 * traQ v3
 *
 * traQ v3 API
 *
 * The version of the OpenAPI document: 3.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// QallRoomStateChangedEventState : 変更後のルーム状態

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct QallRoomStateChangedEventState {
    /// ルームのID
    #[serde(rename = "roomId", skip_serializing_if = "Option::is_none")]
    pub room_id: Option<uuid::Uuid>,
    #[serde(rename = "participants", skip_serializing_if = "Option::is_none")]
    pub participants: Option<Vec<crate::models::QallRoomStateChangedEventStateParticipantsInner>>,
    /// ウェビナールームかどうか
    #[serde(rename = "isWebinar", skip_serializing_if = "Option::is_none")]
    pub is_webinar: Option<bool>,
    /// ルームに関連付けられたカスタム属性
    #[serde(rename = "metadata", skip_serializing_if = "Option::is_none")]
    pub metadata: Option<String>,
}

impl QallRoomStateChangedEventState {
    /// 変更後のルーム状態
    pub fn new() -> QallRoomStateChangedEventState {
        QallRoomStateChangedEventState {
            room_id: None,
            participants: None,
            is_webinar: None,
            metadata: None,
        }
    }
}
