/*
 * traQ v3
 *
 * traQ v3 API
 *
 * The version of the OpenAPI document: 3.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct QallRoomStateChangedEventRoomStatesInnerParticipantsInner {
    /// ユーザーID_RandomUUID
    #[serde(rename = "identity")]
    pub identity: String,
    /// 表示名
    #[serde(rename = "name")]
    pub name: String,
    /// 参加した時刻
    #[serde(rename = "joinedAt")]
    pub joined_at: String,
    #[serde(rename = "attributes", skip_serializing_if = "Option::is_none")]
    pub attributes: Option<::std::collections::HashMap<String, String>>,
    /// 発言権限
    #[serde(rename = "canPublish")]
    pub can_publish: bool,
}

impl QallRoomStateChangedEventRoomStatesInnerParticipantsInner {
    pub fn new(
        identity: String,
        name: String,
        joined_at: String,
        can_publish: bool,
    ) -> QallRoomStateChangedEventRoomStatesInnerParticipantsInner {
        QallRoomStateChangedEventRoomStatesInnerParticipantsInner {
            identity,
            name,
            joined_at,
            attributes: None,
            can_publish,
        }
    }
}
