/*
 * traQ v3
 *
 * traQ v3 API
 *
 * The version of the OpenAPI document: 3.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// QallRoomStateChangedEvent : Qallのルーム状態が変更された

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct QallRoomStateChangedEvent {
    #[serde(rename = "roomStates")]
    pub room_states: Vec<crate::models::QallRoomStateChangedEventRoomStatesInner>,
}

impl QallRoomStateChangedEvent {
    /// Qallのルーム状態が変更された
    pub fn new(
        room_states: Vec<crate::models::QallRoomStateChangedEventRoomStatesInner>,
    ) -> QallRoomStateChangedEvent {
        QallRoomStateChangedEvent { room_states }
    }
}
