/*
 * traQ v3
 *
 * traQ v3 API
 *
 * The version of the OpenAPI document: 3.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct QallMetadataResponse {
    /// ルームに関連付けられたカスタム属性
    #[serde(rename = "metadata", skip_serializing_if = "Option::is_none")]
    pub metadata: Option<String>,
}

impl QallMetadataResponse {
    pub fn new() -> QallMetadataResponse {
        QallMetadataResponse { metadata: None }
    }
}
