/*
 * traQ v3
 *
 * traQ v3 API
 *
 * The version of the OpenAPI document: 3.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct QallTokenResponse {
    /// LiveKit用のJWTトークン
    #[serde(rename = "token")]
    pub token: String,
}

impl QallTokenResponse {
    pub fn new(token: String) -> QallTokenResponse {
        QallTokenResponse { token }
    }
}
