/*
 * traQ v3
 *
 * traQ v3 API
 *
 * The version of the OpenAPI document: 3.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct QallParticipantResponse {
    #[serde(rename = "results", skip_serializing_if = "Option::is_none")]
    pub results: Option<Vec<crate::models::QallParticipantResponseResultsInner>>,
}

impl QallParticipantResponse {
    pub fn new() -> QallParticipantResponse {
        QallParticipantResponse { results: None }
    }
}
