/*
 * traQ v3
 *
 * traQ v3 API
 *
 * The version of the OpenAPI document: 3.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct QallEndpointResponse {
    /// LiveKitのエンドポイント
    #[serde(rename = "endpoint")]
    pub endpoint: String,
}

impl QallEndpointResponse {
    pub fn new(endpoint: String) -> QallEndpointResponse {
        QallEndpointResponse { endpoint }
    }
}
