/*
 * traQ v3
 *
 * traQ v3 API
 *
 * The version of the OpenAPI document: 3.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct QallParticipantRequestUsersInner {
    /// ユーザーID
    #[serde(rename = "userId", skip_serializing_if = "Option::is_none")]
    pub user_id: Option<String>,
    /// 発言権限
    #[serde(rename = "canPublish", skip_serializing_if = "Option::is_none")]
    pub can_publish: Option<bool>,
}

impl QallParticipantRequestUsersInner {
    pub fn new() -> QallParticipantRequestUsersInner {
        QallParticipantRequestUsersInner {
            user_id: None,
            can_publish: None,
        }
    }
}
