/*
 * traQ v3
 *
 * traQ v3 API
 *
 * The version of the OpenAPI document: 3.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct QallParticipantRequest {
    #[serde(rename = "users")]
    pub users: Vec<crate::models::QallParticipantRequestUsersInner>,
}

impl QallParticipantRequest {
    pub fn new(
        users: Vec<crate::models::QallParticipantRequestUsersInner>,
    ) -> QallParticipantRequest {
        QallParticipantRequest { users }
    }
}
