/*
 * traQ v3
 *
 * traQ v3 API
 *
 * The version of the OpenAPI document: 3.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// QallSoundboardItemDeletedEvent : Qallのサウンドボードアイテムが削除された

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct QallSoundboardItemDeletedEvent {
    /// 削除されたサウンドボードアイテムのId
    #[serde(rename = "soundId", skip_serializing_if = "Option::is_none")]
    pub sound_id: Option<uuid::Uuid>,
}

impl QallSoundboardItemDeletedEvent {
    /// Qallのサウンドボードアイテムが削除された
    pub fn new() -> QallSoundboardItemDeletedEvent {
        QallSoundboardItemDeletedEvent { sound_id: None }
    }
}
