/*
 * traQ v3
 *
 * traQ v3 API
 *
 * The version of the OpenAPI document: 3.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// QallRoomStateChangedEvent : Qallのルーム状態が変更された

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct QallRoomStateChangedEvent {
    /// 変更されたルームのId
    #[serde(rename = "room_id")]
    pub room_id: uuid::Uuid,
    #[serde(rename = "state")]
    pub state: Box<crate::models::QallRoomStateChangedEventState>,
}

impl QallRoomStateChangedEvent {
    /// Qallのルーム状態が変更された
    pub fn new(
        room_id: uuid::Uuid,
        state: crate::models::QallRoomStateChangedEventState,
    ) -> QallRoomStateChangedEvent {
        QallRoomStateChangedEvent {
            room_id,
            state: Box::new(state),
        }
    }
}
