/*
 * traQ v3
 *
 * traQ v3 API
 *
 * The version of the OpenAPI document: 3.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// QallParticipant : ルーム内の参加者一覧

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct QallParticipant {
    /// ユーザーID_RandomUUID
    #[serde(rename = "identity", skip_serializing_if = "Option::is_none")]
    pub identity: Option<String>,
    /// 表示名
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// 参加した時刻
    #[serde(rename = "joinedAt", skip_serializing_if = "Option::is_none")]
    pub joined_at: Option<String>,
    /// ユーザーに関連付けられたカスタム属性
    #[serde(rename = "attributes", skip_serializing_if = "Option::is_none")]
    pub attributes: Option<::std::collections::HashMap<String, String>>,
    /// 発言権限
    #[serde(rename = "canPublish", skip_serializing_if = "Option::is_none")]
    pub can_publish: Option<bool>,
}

impl QallParticipant {
    /// ルーム内の参加者一覧
    pub fn new() -> QallParticipant {
        QallParticipant {
            identity: None,
            name: None,
            joined_at: None,
            attributes: None,
            can_publish: None,
        }
    }
}
