/*
 * traQ v3
 *
 * traQ v3 API
 *
 * The version of the OpenAPI document: 3.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct QallRoomStateChangedEventRoomStatesInner {
    /// ルームのID
    #[serde(rename = "roomId")]
    pub room_id: uuid::Uuid,
    #[serde(rename = "participants")]
    pub participants: Vec<crate::models::QallRoomStateChangedEventRoomStatesInnerParticipantsInner>,
    /// ウェビナールームかどうか
    #[serde(rename = "isWebinar")]
    pub is_webinar: bool,
    /// ルームに関連付けられたカスタム属性
    #[serde(rename = "metadata", skip_serializing_if = "Option::is_none")]
    pub metadata: Option<String>,
}

impl QallRoomStateChangedEventRoomStatesInner {
    pub fn new(
        room_id: uuid::Uuid,
        participants: Vec<crate::models::QallRoomStateChangedEventRoomStatesInnerParticipantsInner>,
        is_webinar: bool,
    ) -> QallRoomStateChangedEventRoomStatesInner {
        QallRoomStateChangedEventRoomStatesInner {
            room_id,
            participants,
            is_webinar,
            metadata: None,
        }
    }
}
