/*
 * traQ v3
 *
 * traQ v3 API
 *
 * The version of the OpenAPI document: 3.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SoundboardItem {
    /// サーバが発行したサウンドID
    #[serde(rename = "soundId")]
    pub sound_id: String,
    /// ユーザが指定した表示用のサウンド名
    #[serde(rename = "soundName")]
    pub sound_name: String,
    /// 任意のスタンプID等、サウンドに紐づく拡張情報
    #[serde(rename = "stampId")]
    pub stamp_id: String,
    /// 作成者のユーザID
    #[serde(rename = "creatorId")]
    pub creator_id: String,
}

impl SoundboardItem {
    pub fn new(
        sound_id: String,
        sound_name: String,
        stamp_id: String,
        creator_id: String,
    ) -> SoundboardItem {
        SoundboardItem {
            sound_id,
            sound_name,
            stamp_id,
            creator_id,
        }
    }
}
