/*
 * traQ v3
 *
 * traQ v3 API
 *
 * The version of the OpenAPI document: 3.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SoundboardPlayRequest {
    /// サウンドID (DB登録済み)
    #[serde(rename = "soundId")]
    pub sound_id: String,
    /// 再生させたいルームのUUID
    #[serde(rename = "roomName")]
    pub room_name: uuid::Uuid,
}

impl SoundboardPlayRequest {
    pub fn new(sound_id: String, room_name: uuid::Uuid) -> SoundboardPlayRequest {
        SoundboardPlayRequest {
            sound_id,
            room_name,
        }
    }
}
