/*
 * traQ v3
 *
 * traQ v3 API
 *
 * The version of the OpenAPI document: 3.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SoundboardUploadResponse {
    /// 登録されたサウンドID (ファイル名)
    #[serde(rename = "soundId")]
    pub sound_id: String,
}

impl SoundboardUploadResponse {
    pub fn new(sound_id: String) -> SoundboardUploadResponse {
        SoundboardUploadResponse { sound_id }
    }
}
