/*
 * traQ v3
 *
 * traQ v3 API
 *
 * The version of the OpenAPI document: 3.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SoundboardPlayResponse {
    /// 作成された Ingress のID
    #[serde(rename = "ingressId")]
    pub ingress_id: String,
    /// 作成された Ingress のストリームURL等
    #[serde(rename = "url", skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
    /// RTMP配信の場合のstream key
    #[serde(rename = "streamKey", skip_serializing_if = "Option::is_none")]
    pub stream_key: Option<String>,
}

impl SoundboardPlayResponse {
    pub fn new(ingress_id: String) -> SoundboardPlayResponse {
        SoundboardPlayResponse {
            ingress_id,
            url: None,
            stream_key: None,
        }
    }
}
